### ISSUE TITLE
Black border around plank dock, menu and certain gui windows.

### ISSUE THREAD

**Issue by aurickk** [techcoder20/MacOSBigSurThemeConverter#15]
![image](https://user-images.githubusercontent.com/68048847/145714236-a5a719e1-a63b-4306-a3f9-24e32132519c.png)

It worked fine but it look like this after I reboot it, looks like something wrong with the compositor like this video:
https://www.youtube.com/watch?v=zIZ5XwmdzgU
But I do not know how to configure it.

Here with another example of the black border around files
![image](https://user-images.githubusercontent.com/68048847/145714548-b4d2d0bd-dcd4-48b9-88cc-a6fa891588df.png)

This is on raspian 64bit 
raspberry pi 4 model b 8gm ram

**Comment by techcoder20** [comment]
is compton running ?

**Comment by aurickk** [comment]
Hi I just reboot the system and it worked fine. But how do I check if compton is running?

**Comment by techcoder20** [comment]
There are many ways to check but a simple one is to just run compton in a termianl and see if it complains that another compositor is running.
