### ISSUE TITLE
E: xfce4-statusnotifier-plugin package find fail

### ISSUE THREAD

**Issue by RlabsLLC** [techcoder20/MacOSBigSurThemeConverter#18]
I would love to use this mod to make the pi I'm using to look like an Apple... But I need this issue here to be fixed

**Comment by TankyFranky** [comment]
I am running into an identical issue. 

running the installation provides the following error:
`E: unable to locate package xfce4-statusnotifier-plugin`

`Failed to install dependencies`

Any information on why it is required or how it could be modified would be great.

Thank you.

**Comment by RlabsLLC** [comment]
the theme doesn't work for RaspbainOS 64-bit. try using 32-Bit!

**Comment by RlabsLLC** [comment]
its been found that the xfce4-statusnotifier-plugin package is not
supported OR added to 64-Bit Raspberry Pi OS. BUT, it works for 32-Bit like
how it says on pi-apps.io.
