### ISSUE TITLE
Installation only works for pi user

### ISSUE THREAD

**Issue by hans-martijn** [techcoder20/MacOSBigSurThemeConverter#7]
At (as I guess) almost the end, I get the following error:

Traceback (most recent call last):
  File "/home/hans/.local/share/MacOSBigSurThemeConverter/gui.py", line 8, in <module>
    WindowIcon = PhotoImage(file = '/home/pi/.local/share/MacOSBigSurThemeConverter/assets/Icons/MacOSBigSurThemeConverterLogo.png')
  File "/usr/lib/python3.7/tkinter/__init__.py", line 3545, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "/usr/lib/python3.7/tkinter/__init__.py", line 3501, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
_tkinter.TclError: couldn't open "/home/pi/.local/share/MacOSBigSurThemeConverter/assets/Icons/MacOSBigSurThemeConverterLogo.png": no such file or directory

As you can guess I'm Hans, but it tries to copy from the pi user home dir.

-Hans

**Comment by techcoder20** [comment]
Can you replace the gui file with this and try again. This is a experimental gui which works with every user.

[gui.zip](https://github.com/techcoder20/MacOSBigSurThemeConverter/files/6096507/gui.zip)

**Comment by hans-martijn** [comment]
Yes, that worked.

Thank you very much for the quick response!!!

-Hans

**Comment by hans-martijn** [comment]
Problem solved.

**Comment by hans-martijn** [comment]
sorry, since I tested it with the pi - user, it did work when I tried as myself. Now, with a new installation, I get the following:

mkdir: cannot create directory ‘/home/hans/.local/share/MacOSBigSurThemeConverter’: No such file or directory
mkdir: cannot create directory ‘/home/hans/.local/share/MacOSBigSurThemeConverter/.config_backup’: No such file or directory
cp: cannot create directory '/home/hans/.local/share/MacOSBigSurThemeConverter/.config_backup': No such file or directory
cp: cannot stat '/home/hans/.config/lxsession': No such file or directory
cp: cannot create directory '/home/hans/.local/share/MacOSBigSurThemeConverter/.config_backup': No such file or directory
cp: cannot stat '/home/hans/.config/pcmanfm': No such file or directory
cp: target '/home/hans/.local/share/MacOSBigSurThemeConverter' is not a directory

It looks like now everything is in my home directory.

**Comment by techcoder20** [comment]
What happens when you execute `ls ~/.local/share/`

**Comment by hans-martijn** [comment]
It's not there. I reinstalled the pi, because everything was a bit distorted after testing another program. I created the directories manually and now the installation works again.

**Comment by techcoder20** [comment]
Nice happy it works :)
