### ISSUE TITLE
striped my raspi back to basic gnome.....

### ISSUE THREAD

**Issue by donnerkebab1730** [techcoder20/MacOSBigSurThemeConverter#9]
it had an error on pi apps so in uninstalled and was planning to reinstall until it reverted me back to plane gnome and i have tried and failed to fix it

**Comment by donnerkebab1730** [comment]
update managed to get it fixed

**Comment by donnerkebab1730** [comment]
by uninstalling something else and reinstalling something else, closing this now.......

**Comment by Itai-Nelken** [comment]
did you run this on gnome? I think it only works on lxde

**Comment by donnerkebab1730** [comment]
idk because it took it back to basic desktop and i could see the gnome simble in the corner, however i think it was 2 themes clashing and you had to do some weird stuff but i eventually got it installed
